name: 'lastfm to markdown'
author: 'melipass'
description: 'Adds your Last.fm Weekly Chart to your GitHub Profile or any repo with a README.md'
inputs:
  LASTFM_API_KEY:
    description: 'Last.fm API Key. Store it as a GitHub Secret.'
    required: true
    default: LASTFM_API_KEY

  LASTFM_USER:
    description: 'Last.fms user to get their weekly chart.'
    required: true
    default: LASTFM_USER

  GITHUB_TOKEN:
    description: 'Your GitHub token to push to the repo.'
    required: true
    default: GITHUB_TOKEN
runs:
  using: 'composite'
  steps:
    - env:
        LASTFM_API_KEY: ${{ inputs.LASTFM_API_KEY }}
        LASTFM_USER: ${{ inputs.LASTFM_USER }}
      run: python ${{ github.action_path }}/lastfm.py
      shell: bash
    - name: commit changes
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Updated last.fm's weekly chart" -a

    - name: push changes
      continue-on-error: true
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}\
        branch: main
branding:
  icon: 'music'
  color: 'red'
