name: 'lastfm to markdown'
author: 'melipass'
description: 'Adds your Last.fm Weekly Chart to your GitHub Profile or any repo with a README.md'
runs:
  using: 'composite'
  steps:
    - name: run lastfm to markdown script
      run: python ${{ github.action_path }}/lastfm.py ${{ secrets.LASTFM_API_KEY }} ${{ secrets.LASTFM_USER }}
      shell: bash
    - name: commit changes
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Updated last.fm's weekly chart" -a
    - name: push changes
      continue-on-error: true
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}\
        branch: main
branding:
  icon: 'music'
  color: 'red'
