name: 'lastfm to markdown'
author: 'melipass'
description: 'Adds your Last.fm's Weekly Chart to your GitHub Profile (or any repo with a README.md)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'music'
  color: 'red'
