name: 'lastfm to markdown'
author: 'melipass'
description: 'Adds your Last.fm Weekly Chart to your GitHub Profile or any repo with a README.md'
inputs:
  LASTFM_API_KEY:
    description: 'Last.fm API Key. Store it as a GitHub Secret.'
    required: true
    default: LASTFM_API_KEY

  LASTFM_USER:
    description: 'Last.fms user to get their weekly chart.'
    required: true
    default: LASTFM_USER
    
  IMAGE_COUNT:
    description: 'How many album covers will appear.'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - env:
        LASTFM_API_KEY: ${{ inputs.LASTFM_API_KEY }}
        LASTFM_USER: ${{ inputs.LASTFM_USER }}
        IMAGE_COUNT: ${{ inputs.IMAGE_COUNT }}
      run: python ${{ github.action_path }}/lastfm.py
      shell: bash
      
branding:
  icon: 'music'
  color: 'red'
