name: 'lastfm to markdown'
author: 'melipass'
description: 'Adds your Last.fm Weekly Chart to your GitHub Profile or any repo with a README.md'
inputs:
  LASTFM_API_KEY:
    description: 'Last.fm API Key. Store it as a GitHub Secret.'
    required: true
    default: LASTFM_API_KEY

  LASTFM_USER:
    description: 'Last.fms user to get their weekly chart.'
    required: true
    default: LASTFM_USER

  GITHUB_TOKEN:
    description: 'Your GitHub token to push to the repo.'
    required: true
    default: GITHUB_TOKEN
runs:
  using: 'composite'
  steps:
    - env:
        LASTFM_API_KEY: ${{ inputs.LASTFM_API_KEY }}
        LASTFM_USER: ${{ inputs.LASTFM_USER }}
      run: python lastfm.py
      shell: bash
branding:
  icon: 'music'
  color: 'red'
